<?php
include 'auth.php';
include 'db_config.php';

error_reporting(E_ALL);
ini_set('display_errors', 0); // Disable direct error output to keep JSON clean

header('Content-Type: application/json');

// Check if the logged-in user is allowed to generate reports
if (!isset($_SESSION['role']) || !in_array($_SESSION['role'], ['Admin', 'Manager'])) {
    echo json_encode(["error" => "Unauthorized access"]);
    exit();
}

// Fetch parameters from the request
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $reportType = $_POST['reportType'] ?? '';
    $userID = $_SESSION['user_id'] ?? 0;
    $dateRangeStart = $_POST['dateRangeStart'] ?? '';
    $dateRangeEnd = $_POST['dateRangeEnd'] ?? '';

    if (empty($reportType) || empty($dateRangeStart) || empty($dateRangeEnd)) {
        echo json_encode(["error" => "Missing required parameters (Type, Start Date, or End Date)"]);
        exit();
    }

    // Ensure database connection is available from db_config.php
    if (!isset($conn) || $conn->connect_error) {
        echo json_encode(["error" => "Database connection failed"]);
        exit();
    }

    // Determine the correct query and column for date filtering based on report type
    switch ($reportType) {
        case 'sales':
            $query = "SELECT * FROM salestransaction WHERE SaleDate BETWEEN ? AND ?";
            $reportTitle = "Sales Report";
            break;
        case 'inventory':
            $query = "SELECT * FROM inventoryitem WHERE UpdatedAt BETWEEN ? AND ?";
            $reportTitle = "Inventory Status Report";
            break;
        case 'supplier':
            $query = "SELECT * FROM supplier WHERE UpdatedAt BETWEEN ? AND ?";
            $reportTitle = "Supplier Information Report";
            break;
        case 'predictive':
            $query = "SELECT * FROM prediction WHERE UpdatedAt BETWEEN ? AND ?";
            $reportTitle = "Predictive Analysis History Report";
            break;
        case 'financial':
            $query = "SELECT * FROM salestransaction WHERE SaleDate BETWEEN ? AND ?";
            $reportTitle = "Financial Performance Report";
            break;
        default:
            echo json_encode(["error" => "Unsupported report type: " . htmlspecialchars($reportType)]);
            exit();
    }

    // Prepare and execute the query
    $stmt = $conn->prepare($query);
    if (!$stmt) {
        echo json_encode(["error" => "Query preparation failed: " . $conn->error]);
        exit();
    }

    $stmt->bind_param("ss", $dateRangeStart, $dateRangeEnd);
    if (!$stmt->execute()) {
        echo json_encode(["error" => "Query execution failed: " . $stmt->error]);
        exit();
    }

    $result = $stmt->get_result();
    $rowCount = $result->num_rows;

    // Fetch report data and save it to a formatted file
    $timestamp = date('Y_m_d_H_i_s');
    $fileName = $reportType . '_report_' . $timestamp . '.txt';
    $reportDir = 'reports/';
    
    if (!is_dir($reportDir)) {
        mkdir($reportDir, 0777, true);
    }
    
    $filePath = $reportDir . $fileName;

    $file = fopen($filePath, 'w');
    if (!$file) {
        echo json_encode(["error" => "Could not create report file. Check directory permissions."]);
        exit();
    }

    // Write Report Header
    fwrite($file, "====================================================\n");
    fwrite($file, "           SMART INVENTORY MANAGEMENT SYSTEM         \n");
    fwrite($file, "====================================================\n");
    fwrite($file, "REPORT TYPE: " . strtoupper($reportTitle) . "\n");
    fwrite($file, "GENERATED BY: " . ($_SESSION['username'] ?? 'System') . "\n");
    fwrite($file, "GENERATED ON: " . date('Y-m-d H:i:s') . "\n");
    fwrite($file, "PERIOD: $dateRangeStart TO $dateRangeEnd\n");
    fwrite($file, "TOTAL RECORDS: $rowCount\n");
    fwrite($file, "====================================================\n\n");

    if ($rowCount > 0) {
        while ($row = $result->fetch_assoc()) {
            foreach ($row as $key => $value) {
                $formattedKey = str_pad(str_replace('_', ' ', $key) . ":", 20);
                fwrite($file, "$formattedKey $value\n");
            }
            fwrite($file, "----------------------------------------------------\n");
        }
    } else {
        fwrite($file, "No records found for the selected period.\n");
    }
    
    fwrite($file, "\n*** End of Report ***\n");
    fclose($file);

    // Store the report record in the database
    // We store the filename in the ReportType column as per existing schema behavior, 
    // but ideally, we'd store the type and filename separately.
    $stmtInsert = $conn->prepare("INSERT INTO Report (UserID, ReportType, DateRangeStart, DateRangeEnd) VALUES (?, ?, ?, ?)");
    if ($stmtInsert) {
        $stmtInsert->bind_param("isss", $userID, $fileName, $dateRangeStart, $dateRangeEnd);
        if ($stmtInsert->execute()) {
            $reportID = $stmtInsert->insert_id;
            echo json_encode([
                "success" => true, 
                "reportID" => $reportID, 
                "reportFile" => $fileName,
                "message" => "Report generated successfully."
            ]);
        } else {
            echo json_encode(["error" => "Report generated but failed to save record: " . $stmtInsert->error]);
        }
        $stmtInsert->close();
    } else {
        echo json_encode(["error" => "Failed to prepare database record: " . $conn->error]);
    }

    $stmt->close();
} else {
    echo json_encode(["error" => "Invalid request method."]);
}
?>
